<!-- STYLES -->
<link rel="stylesheet" href="<?=$this->baseUrl();?>/public/css/normalize.css">
<link rel="stylesheet" href="<?=$this->baseUrl();?>/public/css/font.css">
<link rel="stylesheet" href="<?=$this->baseUrl();?>/public/css/main.css">

<!-- JAVASCRIPT -->
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/js/vendor/jquery.min.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/js/vendor/modernizr.min.js"></script>

<script type="text/javascript" src="<?=$this->baseUrl();?>/public/js/plugins.js"></script>
<script type="text/javascript" src="<?=$this->baseUrl();?>/public/js/main.js"></script>

<!-- JAVASCRIPT GLOBAL -->
<script type="text/javascript">
    var path	= '<?=$this->baseUrl();?>',
        url     = '<?=$this->serverUrl().$this->baseUrl();?>',
        ajax    = '<?=$this->serverUrl().$this->baseUrl().'/ajax/';?>';
</script>