<!-- META TAGS DEFAULT -->
<meta charset="utf-8">
<meta name="language" content="pt-br" />
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="robots" content="index,follow,all" />

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width">

<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

<!-- META TAGS FACEBOOK -->
<meta property="og:title" content="" />
<meta property="og:site_name" content="" />
<meta property="og:description" content="" />
<meta property="og:image" content="" />
<meta property="og:url" content="" />
<meta property="og:type" content="" />
<meta property="fb:app_id" content="" />

<!-- META TAGS GOOGLE PLUS -->




<?=$this->meuNome;?>