<html>
    <head>
        <title>Ops!</title>
        <style>
            body{
                background-color: #efefef;
                text-align: center;
                color: #555;
                font: 12px Arial;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <h1>Ops, ocorreu um erro</h1>
        <h2><?php echo $this->message ?></h2>
      
        <?php if (isset($this->exception)): ?>
      
        <h3>Exception information:</h3>
        <p>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
        </p>
      
        <h3>Stack trace:</h3>
        <pre><?php echo $this->exception->getTraceAsString() ?>
        </pre>
      
        <h3>Request Parameters:</h3>
        <pre><?php echo var_export($this->request->getParams(), true) ?>
        </pre>
        <?php endif ?>
    </body>
</html>